whatsapp:
  # WhatsApp Business API credentials
  api_version: "v17.0"  # Meta API version
  phone_number_id: ""   # Your WhatsApp Business Account phone number ID
  access_token: ""      # Your WhatsApp Business API access token
  
  # Group settings
  group_id: ""          # The ID of your WhatsApp group
  
  # Schedule settings
  summary_time: "08:00" # Time to send daily summary (24-hour format)
  timezone: "UTC"       # Your timezone (e.g., UTC, America/New_York)
  
  # Message settings
  summary_format: |
    📝 *Daily Group Summary*
    Date: {date}
    
    {summary}
    
    #DailySummary 