---
tasks:
  message_monitoring:
    description: Monitor and process incoming WhatsApp messages
    agent: message_handler
    tools:
      - WhatsAppTool
      - MessageStorage
    schedule: continuous
    dependencies: []

  message_storage:
    description: Store and organize processed messages
    agent: message_handler
    tools:
      - MessageStorage
    schedule: on_message
    dependencies:
      - message_monitoring

  message_analysis:
    description: Analyze message content and extract insights
    agent: summarization_expert
    tools:
      - MessageAnalyzer
    schedule: daily
    dependencies:
      - message_storage

  summary_generation:
    description: Generate and store daily activity summaries
    agent: summarization_expert
    tools:
      - MessageAnalyzer
      - SummaryStorage
    schedule:
      cron: "0 0 * * *"  # Daily at midnight
      timezone: "{timezone}"
    dependencies:
      - message_analysis

  summary_distribution:
    description: Send generated summaries to WhatsApp group
    agent: message_handler
    tools:
      - WhatsAppTool
      - SummaryStorage
    schedule:
      cron: "0 8 * * *"  # Daily at 8 AM
      timezone: "{timezone}"
    dependencies:
      - summary_generation
